version: '3.3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: on-failure
    logging:
      options:
        max-size: 1g