name: Deploy RDS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: './infra'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Authenticate to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 891377373643.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t lanchonete-apiproduto .
          docker tag lanchonete-apiproduto:latest 891377373643.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/lanchonete-apiproduto:latest
          docker push 891377373643.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/lanchonete-apiproduto:latest